### ISSUE TITLE
PHP 5.4 Feature in use

### ISSUE THREAD

**Issue by Flyingmana** [Cotya/magento-composer-installer#43]
this error just got reported:
 Fatal error: Using $this when not in object context in /data/www/www.marmondo.de/htdocs/vendor/magento-hackathon/magento-composer-installer/src/MagentoHackathon/Composer/Magento/ModuleManager.php on line 159

https://github.com/Cotya/magento-composer-installer/blob/3.0/src/MagentoHackathon/Composer/Magento/ModuleManager.php#L159

reason: no $this support in 5.3, got re added in 5.4

https://wiki.php.net/rfc/closures/removal-of-this

https://wiki.php.net/rfc/closures/object-extension

**Comment by Flyingmana** [comment]
question now is, should we increase required version or workaround this?

I would like to increase to 5.5, but dont I dont really care about this.

**Comment by AydinHassan** [comment]
There are quite a lot of square brackets being used also. I'm indifferent, I don't care for 5.3 support.

**Comment by hellosworldos** [comment]
Please increase required version, have just spent some time to figure out what caused the issue. It would be better that composer notify about incompatibility

**Comment by hellosworldos** [comment]
Workaround for the issue is:

```
        $packages = array();
        foreach ($currentComposerInstalledPackages as $package) {
            /* @var $package PackageInterface */
            if (!$repo->has($package->getName(), $this->createVersion($package))) {
                $packages[] = $package;
            }
        }
//        $packages = array_filter($currentComposerInstalledPackages, function(PackageInterface $package) use ($repo) {
//            return !$repo->has($package->getName(), $this->createVersion($package));
//        });
```

Also noticed another one fatal with PHP 5.3: 
Fatal error: Uncaught exception 'ErrorException' with message 'Use of undefined constant JSON_PRETTY_PRINT - assumed 'JSON_PRETTY_PRINT'' in /srv/www/cim/test/build/oyestore/vendor/magento-hackathon/magento-composer-installer/src/MagentoHackathon/Composer/Magento/Repository/InstalledPackageFileSystemRepository.php on line 187

the requirement  for JSON_PRETTY_PRINT is 5.4.0+ as well

**Comment by oliver-graetz** [comment]
There is a best practice to easier work around the closure `$this` problem in PHP 5.3:
```php
$self = $this;
$packages = array_filter($currentComposerInstalledPackages, function(PackageInterface $package) use ($repo, $self) {
    return !$repo->has($package->getName(), $self->createVersion($package));
});
```
I recommend to use the `$self` import of `$this` into closures for projects where PHP 5.3 compatibility is still needed. This makes for a much simpler change when upgrading to PHP 5.4 .

**Comment by ktomk** [comment]
You can best find out about this by providing a requirement of the PHP version in the composer.json so that it's clear on a system what is not satisfied and which component needs it.

E.g. put the current requirement in there (I think this  is PHP 5.4.x) and then make a release. Let it settle in and see which feedback you get. E.g. find out if there are some professionally LTS managed systems that make use of composer installer which have PHP 5.3 with ongoing security support. Or all the other things you can't imagine and then want to decide about. Can also help to find sponsors.

**Comment by Flyingmana** [comment]
solved by readme Paragraph: https://github.com/Cotya/magento-composer-installer#supported-php-versions
